### ISSUE TITLE
unable to pass the token when using the component

### ISSUE THREAD

**Issue by gnzjgo** [tinybirdco/next-tinybird#1]
Error:
```
tracker.js:37 Uncaught Error: token is needed for sending events
    at tracker.js:37:7
    at e (tracker.js:154:3)
    at tracker.js:242:1
    at tracker.js:242:9
```

but token was defined:
```
<TinybirdProvider
    dataSource={'test'}      
    token={process.env.NEXT_PUBLIC_TINYBIRD_TRACKER_TOKEN}
    >
```

**Comment by raqyuste** [comment]
The tracker that is used by default is the one published in this cdn: https://cdn.tinybird.co/static/js/t.js 

But, how are we publishing the tracker to there? Because I don't see any job at the [tracker repo](https://github.com/tinybirdco/tinybird-tracker) that deploys there. The [job](https://github.com/tinybirdco/tinybird-tracker/blob/master/.github/workflows/main.yml) triggered every time we merge in master is running some tests but any "deploy". So, I guess that's the reason why the version is not up to date.

How can I get access to this cdn to publish it there? cc @xavijam

**Comment by xavijam** [comment]
It is "published" in that URL when there is a deploy in Tinybird Analitycs.
